### ISSUE TITLE
Ambiguous use of 'cornerRadius'

### ISSUE THREAD

**Issue by tospery** [SwifterSwift/SwifterSwift#1048]
Many third-party libraries also have cornerRadius for their own view, which causes a conflict when using it. It is recommended that SwifterSwift rename it to cRadius or ss_cornerRadius.

**Comment by MussaCharles** [comment]
This issue was addressed on PR #972 ,and reflected on on the latest [v5.3.0 release](https://github.com/SwifterSwift/SwifterSwift/releases/tag/5.3.0). Be sure to read [v5.3.0 CHANGELOG](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG.md#v530) before updating, as renaming properties is needed as described on [v5.3.0 CHANGELOG](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG.md#v530).
