### ISSUE TITLE
Ambiguous use of 'shadowColor'

### ISSUE THREAD

**Issue by xiaoyao20084321** [SwifterSwift/SwifterSwift#1058]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/10344550/200723818-35a7ca20-631b-4080-9bb1-939d7b739352.png">
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/10344550/200723395-22f97000-8c2d-43cb-8fbb-ddd75a783e74.png">

**Comment by MussaCharles** [comment]
This issue was addressed on PR #897 ,And those breaking changes are reflected on on the latest [v5.3.0 release](https://github.com/SwifterSwift/SwifterSwift/releases/tag/5.3.0). Be sure to read [v5.3.0 CHANGELOG](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG.md#v530). For your current issue, after updating to [v5.3.0](https://github.com/SwifterSwift/SwifterSwift/releases/tag/5.3.0), replace `label.shadowColor` with `label.layerShadowColor`, similarly update all other related properties as specified on [v5.3.0 CHANGELOG](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG.md#v530).

**Comment by Asura19** [comment]
> <img alt="image" width="1215" src="https://user-images.githubusercontent.com/10344550/200723818-35a7ca20-631b-4080-9bb1-939d7b739352.png">
> 
> <img alt="image" width="1240" src="https://user-images.githubusercontent.com/10344550/200723395-22f97000-8c2d-43cb-8fbb-ddd75a783e74.png">

https://github.com/reers/ReerKit   is another choice.
