### ISSUE TITLE
Is codecov report correct?

### ISSUE THREAD

**Issue by tapanprakasht** [SwifterSwift/SwifterSwift#166]
I was looking into codecov report to check how well the code is tested. But I found some disparity between codecov report and Xcode coverage report. For example look at the case of UISliderExtensions.  
This is the codecov report for UISliderExtension where completion handler is not covered by test.
![image](https://cloud.githubusercontent.com/assets/4947384/25581581/57857f40-2ea6-11e7-95b2-aeb7a269d0ae.png)
But when I run the same test in Xcode it is giving the following result where test coverage is 100%
![image](https://cloud.githubusercontent.com/assets/4947384/25581662/bccfe598-2ea6-11e7-94b6-536bc3fa52fe.png)

Did anybody know why this disparity happens? Is it a bug with Codecov? Is there anything to do with xcpretty in travis file? Because following link says broken codecov with xcpretty.
[codecov/example-swift](https://github.com/codecov/example-swift)

**Comment by SD10** [comment]
Hi @tapanprakasht, I'm not sure what the issue is regarding this. If `xcpretty` is indeed causing this issue, we will have to deal with it, because I value being able to read the build log more than hitting every line of code. That being said, I also know that the completion block for `animate(withDuration:)` is finicky. You can see this in the `UITableView` & `UICollectionView` method `reloadData(completion:)`. Although, in this specific case we may need to change the time interval because vaguely from memory - I believe if the duration is zero then the completion won't be called until the next run loop. However, this is a separate issue 😃
