### ISSUE TITLE
DateExtensions.swift:215:27: Type 'Locale!' has no member 'posix'

### ISSUE THREAD

**Issue by canaksoy** [SwifterSwift/SwifterSwift#174]
```Swift
public var iso8601String: String {
		// https://github.com/justinmakaila/NSDate-ISO-8601/blob/master/NSDateISO8601.swift
		let dateFormatter = DateFormatter()
		dateFormatter.locale = .posix
		dateFormatter.timeZone = TimeZone(abbreviation: "GMT")
		dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS"
		
		return dateFormatter.string(from: self).appending("Z")
}
```

DateExtensions.swift:215:27: Type 'Locale!' has no member 'posix'

**Comment by SD10** [comment]
Hey @canaksoy, 

Are you using the SwifterSwift library via CocoaPods or are you manually cutting and pasting this extension? 

The reason I'm asking is that `.posix` is another SwifterSwift extension. 
It's a static property defined in `LocaleExtensions`:

```Swift
public extension Locale {

    /// SwifterSwift: UNIX representation of locale usually used for normalizing.
    public static var posix: Locale {
        return Locale(identifier: "en_US_POSIX")
    }	
}
```

If you are using this extension via copy & paste then you will need this one as well.
Please let me know if this resolves the issue so that I can assure it's not affecting anyone else.

**Comment by omaralbeik** [comment]
@canaksoy I think you had the problem because you copied the extension separately as @SD10 mentioned above, please check the extension back [here](https://github.com/SwifterSwift/SwifterSwift/blob/master/Source/Extensions/DateExtensions.swift) and let me know if you are still facing the same problem

Thank you @SD10!

**Comment by canaksoy** [comment]
No. I'm using cocoapods.. SwifterSwift (1.6.4). I update repo and install again then I think error gone.
