### ISSUE TITLE
Add macOS testing to Travis

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#255]
Right now we are not testing the `SwifterSwift-macOS` scheme on Travis CI, due to the following error:
```
Signing for "SwifterSwift-macOSTests" requires a development team. Select a development team in the project editor.
```

Well, we need to fix this 😅

**Comment by SD10** [comment]
Maybe the `SwifterSwift-macOS` target needs to set Code Signing Identity under Build Settings to Don't Code Sign for Debug/Release

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omaralbeik** [comment]
I did, it was raising another error:

```
No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "XXXXXXXXXX" with a private key was found.
```
even though I have it under my developer account ¯\_(ツ)_/¯.
This started to happen after Travis updated their mac provider recently

**Comment by LucianoPAlmeida** [comment]
@omaralbeik Did you set the SwifterSwift-macOS or the SwifterSwift-macOSTests Code Signing None?

**Comment by omaralbeik** [comment]
@LucianoPAlmeida right now it is none, but I tried settings it to my own account and it didn't work.
It works when I run the tests locally but not when Travis does.

**Comment by LucianoPAlmeida** [comment]
![screen shot 2017-09-28 at 09 57 39](https://user-images.githubusercontent.com/8292651/30967784-ac193030-a433-11e7-987a-555fb90d9dd5.png)
I saw this on the target tests for macos only and thought it might be the problem, but since you already change it ¯_(ツ)_/¯, i'll try to take a look also see if i can find something :)

**Comment by LucianoPAlmeida** [comment]
@omaralbeik I find that the test were not runing localy on my machine because of the same error
![screen shot 2017-09-28 at 10 06 57](https://user-images.githubusercontent.com/8292651/30968170-cef5fe52-a434-11e7-827f-0cb8d59253c8.png)
Fixed it changing the code sign identity of the macOSTest traget from MacDeveloper to Don't Code Sign

**Comment by omaralbeik** [comment]
Thanks @LucianoPAlmeida, will try it today :)
