### ISSUE TITLE
Can't see the extensions

### ISSUE THREAD

**Issue by XRadevFRT** [SwifterSwift/SwifterSwift#359]
### What did you do?
I installed SwifterSwift with cocoapods (I tried to drag & drop the Extensions folder before that, but the result was the same)

### What did you expect to happen?
Well to start seeing and using the extensions

### What happened instead?
Although I see the inspectables in the storyboard, I don't see any of the public methods or properties after the **.** notation

### SwifterSwift Environment

- Xcode version: 9.2
- macOS version running Xcode: Sierra

I really like this library and the documentation for it. I want to use it in the future...so I really need your help!

**Comment by LucianoPAlmeida** [comment]
Hi @XRadevFRT :)
Did you make sure to put the `import SwifterSwift ` statement in the files you are trying to use the extensions?

**Comment by XRadevFRT** [comment]
Hm no, I didn't. Just dropped the Extensions folder in the project, wrote the `import SwifterSwift` but an error **No such module 'SwifterSwift** appeared.

**Comment by Najdan** [comment]
@XRadevFRT it may be bug in Xcode where you drop files into project but **Target Membership** is not set correctly for those files. @LucianoPAlmeida was talking about `CocoaPods` approach of installing **SwifterSwift**. 

Try to drag & drop files again and then check if **Target Membership** is correct in **File Inspector**

**Comment by XRadevFRT** [comment]
After adding the `import SwifterSwift` the features started showing (this is with the cocoapods installation). I got to say this is strange to me. After all the main point of the extensions is the easy feature-usage.
Thank you!
I hope this issue can help others or if someone has a better approach will contribute to this issue.
Happy coding!

**Comment by Najdan** [comment]
@XRadevFRT That's just how `CocoaPods` are designed to work.

Did you tried manual installation (drag & dropping of Sources folder) make sure that **Copy items if needed** is selected and select targets where you want to use extension. If you are using older version of Xcode it had bug where dropping multiple files into project and selecting targets didn't actually set targets (nothing was selected when you check **Target Membership**) for that file and extension are not visible because of that.

If **Target Membership** is set correctly you should be able to use extensions, try `Date().nanosecond` to see if it's available.

If it's working for you with **CocoaPods** approach you can keep using it. To make extensions available everywhere in code try to `import SwifterSwift` in `AppDelegate.swift` file.

I'm glad that you found solution that works for you 🙂

**Comment by LucianoPAlmeida** [comment]
Thank you @Najdan :)

**Comment by rfadams** [comment]
@LucianoPAlmeida Thanks for the awesome library! :) 

FWIW: that you have to `import SwifterSwift` either in the file you want to use it or in `AppDelegate.swift` was not obvious to me either and I spent 20 (frustrating) mins of checking and re-checking my Carthage install before finding this issue. 

I'm new to Swift and so maybe it would be more obvious to more experienced developers, but a bit of documentation in the "Installation" section(s), would go a long way. 

Thanks again. Cheers.

**Comment by LucianoPAlmeida** [comment]
Hey @rfadams, 
In name of all @SwifterSwift/contributors, we are glad you like it :)) 
And about the Installation additional is noted and we can work on that as soon as possible 👍 
But feel free to send a PR with this improvement if you like :))

**Comment by rafalellys** [comment]
Hi there,
Thanks, SwifterSwift is super awesome but I think you replied this message
to the wrong person. :)) My github handle is @rafalellys
<rafalellys@gmail.com>
Cheers! ;)
