### ISSUE TITLE
Add an extension to get thumbnail image from a video URL

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#360]
Add an extension to `UIImage` to generate a thumbnail image from a video URL using `AVAssetImageGenerator` from `AVFoundation`

**Comment by BennX** [comment]
@omaralbeik I'd like to propsose this as a URL extension since UIImage generating a UIImage seems weird. It would look like `let thumbnail = URL(string: "path/to/resource").thumbnail()`. Taking a optional seconds in parameter and is returning an `UIImage?`. Furthermore I'd like to propse `URL(string: "path/to/resource").thumbnail() { UIImage? in  }` since requesting a the resource may take some time.

I got a PR ready just thinking about the testing here. Any ideas since I'm not that confident if it makes sense to test for nil / not nil?
