### ISSUE TITLE
A convenient way to get keyboard size, animation duration, start frame and end frame from Notification

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#476]
You know, iOS sends notifications for keyboard events. I was wondering if we can use extensions to get information from notifications by extending the type `Notification`. all properties should be optional since the notification might be not for a keyboard event.

**Comment by LucianoPAlmeida** [comment]
Hey @omaralbeik :)) 
I'm not sure if extending notification for this kind of functionality is an aproach that makes sense in a type abstaction. Mostly because of doing that, I think we kind of assuming that a Notification, that is a more generic class that abstracts a system notification have some that have a relation to keyboard. 
For this kind of functionality I'll probably go for something like:
```swift
class KeyboardEvent {
    private var note: Notification
    private(set) var keyBoardFrame: CGRect?

    init(notification: Notification) {
       /// populate all the properties 
    }
}
// So using will be readable and clear, saying that we might be able to construct a keyboard event with
// a note, and once we have a KeyboardEvent we may access the keyboard properties.
@objc keyboardWillHide(_ note: Notification) {
    let keyboardEvent = KeyboardEvent(notification: note )
    let keyboardFrame = keyboardEvent.keyBoardFrame
}
```
I don't know, maybe I'm being to verbose with this 😂 where just extending the notification will be way more simple 😂But I think with something like this we avoid coupling a generic Notification type to keyboard event and make usage more clear. But maybe I'm making something that should be simple too much complex 😅
Let me know your toughts about this? @omaralbeik 
Also this solution do not applies to SwifterSwift I think, because it requires a new type :(( 
So maybe just extending notification is sufficient. And also I'm starting to get confused with my own toughts 🤣 🤣 🤣

**Comment by SD10** [comment]
IMO we shouldn't add new types to SwifterSwift. We should only provide extensions on Apple libraries
