### ISSUE TITLE
init for jsonDate (c#)

### ISSUE THREAD

**Issue by furiosFast** [SwifterSwift/SwifterSwift#825]
hi,
Hello,
I suggest adding this extension which can come in handy when dealing with dates obtained from c#
```Swift
extension Date {
   
    init?(jsonDate: String) {
        
        let pattern = #"\\?/Date\((\d+)([+-]\d{4})?\)\\?/"#
        let regex = try! NSRegularExpression(pattern: pattern)
        guard let match = regex.firstMatch(in: jsonDate, range: NSRange(jsonDate.startIndex..., in: jsonDate)) else {
            return nil
        }
        
        // Extract milliseconds:
        let dateString = jsonDate[Range(match.range(at: 1), in: jsonDate)!]
        // Convert to UNIX timestamp in seconds:
        let timeStamp = Double(dateString)! / 1000.0
        // Create Date from timestamp:
        self.init(timeIntervalSince1970: timeStamp)
    }
    
}
```

**Comment by guykogus** [comment]
You're interoperating between C# and Swift? That's interesting. Can you share an example of how exactly the C# dates appear as strings? This is a very curious case.

**Comment by furiosFast** [comment]
inside the json:
...
`
"startDate": "\/Date(1420066800000)\/",
`
...

**Comment by guykogus** [comment]
It sounds more like C# should be formatting the dates properly when they send it to JSON, either in ISO8601 or as epoch time (or, heavens forbid, RFC3339 😬). Otherwise this extension seems like a very specific issue caused elsewhere and wouldn't really belong in SwifterSwift, which is a general-purpose library.
