### ISSUE TITLE
proposed String extensions

### ISSUE THREAD

**Issue by gurgeous** [SwifterSwift/SwifterSwift#898]
Same as before. Give me a bit of feedback and I'll put together a PR if there's interest. Two methods:

```swift
// like base64Encoded, but safe for URL parameters
// https://en.wikipedia.org/wiki/Base64#URL_applications
var base64UrlEncoded: String?`

// collapses runs of whitespace to a space, then trims. Helpful for normalizing user input.
var squished: String
```

**Comment by guykogus** [comment]
`String` already has a `base64Encoded` property.
`squished` sounds nice, but I usually find the only requirement is to trim white spaces, and we have the `trimmed` property for that.

**Comment by gurgeous** [comment]
`base64UrlEncoded` is different from `base64Encoded`. It's a variant for url query parameters. Something like:

```swift
var base64UrlEncoded: String? {
    guard let s = base64Encoded else {
      return nil
    }

    // https://en.wikipedia.org/wiki/Base64#URL_applications
    let map = ["+": "-", "/": "_", "=": ""]
    return map.reduce(s) { $0.replacingOccurrences(of: $1.0, with: $1.1) }
  }
```

`squished` normalizes all whitespace, including runs of whitespace:

`"  hello    world  " => "hello world"`

This cleans up many common user input errors. We don't need it, though.

**Comment by guykogus** [comment]
I still don't understand the use case of `base64UrlEncoded`. Can you please show an example?

**Comment by gurgeous** [comment]
The problem arises when you want to send a URL query parameter with base 64 encoded data, like `a` = `base64("something")`:

`base64("something")` => `"c29tZXRoaW5n"`

or

`https://example.com/q?a=c29tZXRoaW5n`

but what if the value of `a` is `base64("q0?ml")`? The standard base 64 encoding is:

`base64("q0?ml")` => `"cTA/bWw="`

If you aren't careful the URL will become something invalid like:

`https://example.com/q?a=cTA/bWw=`

To avoid this problem you have to URL encode the base 64 encoded value, which would then be:

`https://example.com/q?a=cTA%2FbWw%3D`

This is both inefficient and error prone for the unwary. Eventually a variant of base 64 encoding emerged as described here - https://en.wikipedia.org/wiki/Base64#URL_applications. A few characters are altered from the standard base 64 output, to produce:

`https://example.com/q?a=cTA_bWw`

Many languages and libraries support this variant because the use case is so common. In fact, the tool I'm using right now has a button for URL safe encode & decode - https://www.base64encode.org/

We should support it too!

**Comment by gurgeous** [comment]
Just giving this one another nudge... should I proceed? I'm fine if you want to close it and focus energy elsewhere. I won't be offended, I promise 😄

**Comment by LucianoPAlmeida** [comment]
Sorry we've missed that @gurgeous, I'll try to take a look at this soon :)

**Comment by LucianoPAlmeida** [comment]
My two cents:
* `base64UrlEncoded`: If I understood correctly, I see that what you may want is to encode the URL escaping the base64 values. I see the point, but I think it would be actually more general to have an extension on the string that does the URL escaping. Think about it that way, instead of a `string.base64UrlEncoded` we could have a `string.base64Encoded.urlEscaped`. This way we could have both functionalities well separated instead of coupled together so we can use `urlEscaped` for other scenarios. 
* `squished`: What is the difference of this and `" hello world ".trimmingCharacters(in: .whitespaces)`? I know that it is `Foundation` stuff, so maybe the idea is to have some native string extension? 

@gurgeous Sorry it took a while, I totally forgot about this 😅
