### ISSUE TITLE
SwifterSwift compilation error when used in an app extension target  

### ISSUE THREAD

**Issue by tospery** [SwifterSwift/SwifterSwift#915]
Because SwifterSwift contains UIApplication, so it can't use in Network Extension.Hope to do a compatibility.

**Comment by LucianoPAlmeida** [comment]
Sorry, I didn't really understand the issue... can you provide a more detailed description and if possible an example?

**Comment by tospery** [comment]
1. When I integrate SwifterSwift into the extension application (Network Extension -> Packet Tunnel)
![image](https://user-images.githubusercontent.com/3716286/98059017-0c3ef880-1e81-11eb-8b6f-0cb4e79853b3.png)
2. Compile project will error:
![image](https://user-images.githubusercontent.com/3716286/98059364-e23a0600-1e81-11eb-9f64-7e03994d3cda.png)

**Comment by LucianoPAlmeida** [comment]
Ah thanks, we'll take a look ASAP :)

**Comment by LucianoPAlmeida** [comment]
Here is a reference https://davedelong.com/blog/2019/04/09/conditional-compilation-part-3/ 
But we actually need a simpler solution to conditionally not compiling for app extensions, I was looking to see if we can mark the whole `show` function as unavailable for app extensions. But still couldn't found how to use or if it is possible to use `NS_EXTENSION_UNAVAILABLE_IOS` on Swift. 

But to be really honest to me personally, this extension should be changed to take the viewController as a parameter. But not sure if we could do that because it will be an breaking change and I suspect people use this.

**Comment by LucianoPAlmeida** [comment]
@tospery Can you verify if changing the function `show` to having the following attribute fixes the issue?
```swift
@available(iOSApplicationExtension, unavailable)
func show(...) ...
```

**Comment by LucianoPAlmeida** [comment]
Fixed on master, feel free to reopen if this still an issue :)
