### ISSUE TITLE
decode base64 string fail

### ISSUE THREAD

**Issue by tospery** [SwifterSwift/SwifterSwift#956]
string as under can decode at https://base64.us/, 
but can't decode string's base64Decoded property

IyBUcnVzdCBXYWxsZXQgQXNzZXRzIEluZm8KCiFbQ2hlY2tdKGh0dHBzOi8v\nZ2l0aHViLmNvbS90cnVzdHdhbGxldC9hc3NldHMvd29ya2Zsb3dzL0NoZWNr\nL2JhZGdlLnN2ZykKCiMjIE92ZXJ2aWV3ClRydXN0IFdhbGxldCB0b2tlbiBy\nZXBvc2l0b3J5IGlzIGEgY29tcHJlaGVuc2l2ZSwgdXAtdG8tZGF0ZSBjb2xs\nZWN0aW9uIG9mIGluZm9ybWF0aW9uIGFib3V0IHNldmVyYWwgdGhvdXNhbmRz\nICghKSBvZiBjcnlwdG8gdG9rZW5zLgoKW1RydXN0IFdhbGxldF0oaHR0cHM6\nLy90cnVzdHdhbGxldC5jb20pIHVzZXMgdG9rZW4gbG9nb3MgZnJvbSB0aGlz\nIHNvdXJjZSwgYWxvbmdzaWRlIGEgbnVtYmVyIG9mIG90aGVyIHByb2plY3Rz\nLgoKVGhlIHJlcG9zaXRvcnkgY29udGFpbnMgdG9rZW4gaW5mbyBmcm9tIHNl\ndmVyYWwgYmxvY2tjaGFpbnMsIGluZm8gb24gZEFwcHMsIHN0YWtpbmcgdmFs\naWRhdG9ycywgZXRjLgpGb3IgZXZlcnkgdG9rZW4gYSBsb2dvIGFuZCBvcHRp\nb25hbCBhZGRpdGlvbmFsIGluZm9ybWF0aW9uIGlzIGF2YWlsYWJsZSAoc3Vj\naCBkYXRhIGlzIG5vdCBhdmFpbGFibGUgb24tY2hhaW4pLgoKU3VjaCBhIGxh\ncmdlIGNvbGxlY3Rpb24gY2FuIGJlIG1haW50YWluZWQgb25seSB0aHJvdWdo\nIGEgY29tbXVuaXR5IGVmZm9ydCwgc28gX2ZlZWwgZnJlZSB0byBhZGQgeW91\nciB0b2tlbl8uCgo8Y2VudGVyPjxpbWcgc3JjPSdodHRwczovL3RydXN0d2Fs\nbGV0LmNvbS9hc3NldHMvaW1hZ2VzL21lZGlhL2Fzc2V0cy9ob3Jpem9udGFs\nX2JsdWUucG5nJyBoZWlnaHQ9IjIwMCI+PC9jZW50ZXI+CgojIyBIb3cgdG8g\nYWRkIHRva2VuCgpQbGVhc2Ugbm90ZSB0aGF0IF9fYnJhbmQgbmV3IHRva2Vu\ncyBhcmUgbm90IGFjY2VwdGVkX18sCnRoZSBwcm9qZWN0cyBoYXZlIHRvIGJl\nIHNvdW5kLCB3aXRoIGluZm9ybWF0aW9uIGF2YWlsYWJsZSwgYW5kIF9fbm9u\nLW1pbmltYWwgY2lyY3VsYXRpb25fXwooZm9yIGxpbWl0IGRldGFpbHMgc2Vl\nIGh0dHBzOi8vY29tbXVuaXR5LnRydXN0d2FsbGV0LmNvbS90L2hvdy10by1z\ndWJtaXQtYS10b2tlbi1sb2dvLzM4NjMpLgoKIyMjIEFzc2V0cyBBcHAKClRo\nZSBbQXNzZXRzIHdlYiBhcHBdKGh0dHBzOi8vYXNzZXRzLnRydXN0d2FsbGV0\nLmNvbSkgY2FuIGJlIHVzZWQgZm9yIG1vc3QgbmV3IHRva2VuIGFkZGl0aW9u\ncyAoR2l0aHViIGFjY291bnQgaXMgbmVlZGVkKS4KCiMjIyBRdWljayBzdGFy\ndGVyCgpEZXRhaWxzIG9mIHRoZSByZXBvc2l0b3J5IHN0cnVjdHVyZSBhbmQg\nY29udHJpYnV0aW9uIGd1aWRlbGluZXMgYXJlIGxpc3RlZCBvbiB0aGUKW0Rl\ndmVsb3BlcnMgc2l0ZV0oaHR0cHM6Ly9kZXZlbG9wZXIudHJ1c3R3YWxsZXQu\nY29tL2FkZF9uZXdfYXNzZXQpLgpIZXJlIGlzIGEgcXVpY2sgc3RhcnRlciBz\ndW1tYXJ5IGZvciB0aGUgbW9zdCBjb21tb24gdXNlIGNhc2UuCgoqKkFkZGlu\nZyBhbiBFUkMyMCB0b2tlbiBjaGVja2xpc3QqKjoKLSBbIF0gTWFrZSBzdXJl\nIHlvdXIgc21hcnRjb250cmFjdCBoYXMgbW9yZSB0aGFuIDIsNTAwIGFkZHJl\nc3MgaG9sZGVycywgb3RoZXJ3aXNlIHlvdSB3aWxsIGJlIHJlamVjdGVkCi0g\nWyBdIEZvcmsgdGhlIEdpdGh1YiByZXBvc2l0b3J5Ci0gWyBdIENyZWF0ZSBm\nb2xkZXIgd2l0aCBuYW1lIG9mIHRva2VuIHNtYXJ0Y29udGFjdCBhZGRyZXNz\nIGluIFtfY2hlY2tzdW0gZm9ybWF0X10oaHR0cHM6Ly9kZXZlbG9wZXIudHJ1\nc3R3YWxsZXQuY29tL2FkZF9uZXdfYXNzZXQjY2hlY2tzdW1fZm9ybWF0KSBg\nYmxvY2tjaGFpbnMvZXRoZXJldW0vYXNzZXRzLzx0b2tlbl9zbWFydGNvbnRy\nYWN0X2FkZHJlc3M+L2AuCi0gWyBdIFRlbGwgeW91ciBkZXNpZ25lciB0aGF0\nIHRva2VuIGltYWdlIG11c3QgYmUgaW4gUE5HIGZvcm1hdCwgYXZvaWQgdHJh\nbnNwYXJlbnQgYmFja2dyb3VuZCwgcmVjb21tZW5kZWQgc2l6ZSAyNTZ4MjU2\ncHgsIG1heC4gNTEyeDUxMnB4LCB3aXRoIG1heCBmaWxlIHNpemUgb2YgMTAw\na0IsIGZvciBmdXJ0aGVyIGRldGFpbHMgcmVhZCBbaW1hZ2UgcnVsZXNdKGh0\ndHBzOi8vZGV2ZWxvcGVyLnRydXN0d2FsbGV0LmNvbS9hZGRfbmV3X2Fzc2V0\nI2ltYWdlLXJlcXVpcmVtZW50cykuCi0gWyBdIFVwbG9hZCB5b3VyIGxvZ28g\nd2l0aCBmaWxlIG5hbWVkIGBsb2dvLnBuZ2AgdG8gcHJldmlvdXNseSBjcmVh\ndGVkIGZvbGRlciB3aXRoIHNtYXJ0Y29udHJhY3QgYWRkcmVzcywgYW5kIGlm\nIHlvdSBkb25lIGFsbCBjb3JyZWN0bHkgeW91ciBwYXRoIHNob3VsZCBsb29r\nIGxpa2UgdGhpcy4gYGJsb2NrY2hhaW5zL2V0aGVyZXVtL2Fzc2V0cy8weDEy\nMzQ1Njc0NjFkM2Y4RGI3NDk2NTgxNzc0QmQ4NjlDODNENTFjOTMvbG9nby5w\nbmdgCi0gWyBdIENyZWF0ZSBgaW5mby5qc29uYCBmaWxlIHdpdGggaW5mbyBh\nYm91dCB0aGUgdG9rZW4vcHJvamVjdAotIFsgXSBDcmVhdGUgYSBwdWxsIHJl\ncXVlc3QgdG8gdGhlIG1haW4gcmVwbwotIFsgXSBQYXkgdGhlIHByb2Nlc3Np\nbmcgZmVlCgojIyBEb2N1bWVudGF0aW9uCgpGb3IgZGV0YWlscywgc2VlIHRo\nZSBbRGV2ZWxvcGVycyBzaXRlXShodHRwczovL2RldmVsb3Blci50cnVzdHdh\nbGxldC5jb20vYWRkX25ld19hc3NldCk6CgotIFtDb250cmlidXRpb24gZ3Vp\nZGVsaW5lc10oaHR0cHM6Ly9kZXZlbG9wZXIudHJ1c3R3YWxsZXQuY29tL2Fk\nZF9uZXdfYXNzZXQjY29udHJpYnV0aW9uLWd1aWRlbGluZXMpCgotIFtSZXBv\nc2l0b3J5IGRldGFpbHNdKGh0dHBzOi8vZGV2ZWxvcGVyLnRydXN0d2FsbGV0\nLmNvbS9hZGRfbmV3X2Fzc2V0I3JlcG9zaXRvcnktZGV0YWlscykKCiMjIFNj\ncmlwdHMKClRoZXJlIGFyZSBzZXZlcmFsIHNjcmlwdHMgYXZhaWxhYmxlIGZv\nciBtYWludGFpbmVyczoKCi0gYG5wbSBydW4gY2hlY2tgIC0tIEV4ZWN1dGUg\ndmFsaWRhdGlvbiBjaGVja3M7IGFsc28gdXNlZCBpbiBjb250aW51b3VzIGlu\ndGVncmF0aW9uLgotIGBucG0gcnVuIGNoZWNrLXNhbml0eWAgLS0gU3RyaWN0\nIHN1YnNldCBvZiBjaGVja3MKLSBgbnBtIHJ1biBmaXhgIC0tIFBlcmZvcm0g\nYXV0b21hdGljIGZpeGVzIHdoZXJlIHBvc3NpYmxlCi0gYG5wbSBydW4gZml4\nLXNhbml0eWAgLS0gU3RyaWN0ZXIgc3Vic2V0Ci0gYG5wbSBydW4gdXBkYXRl\nQXV0b2AgLS0gUnVuIGF1dG9tYXRpYyB1cGRhdGVzIGZyb20gZXh0ZXJuYWwg\nc291cmNlcywgZXhlY3V0ZWQgcmVndWxhcmx5IChHaXRIdWIgYWN0aW9uKQot\nIGBucG0gcnVuIHVwZGF0ZWAgLS0gUnVuIG1hbnVhbCB1cGRhdGVzIGZyb20g\nZXh0ZXJuYWwgc291cmNlcywgZm9yIG1hbnVhbCB1c2UuCi0gYG5wbSB0ZXN0\nYCAtLSBSdW4gc2NyaXB0IHVuaXQgdGVzdHMKLSBgbnBtIGxpbnRgIC0tIFJ1\nbiBMaW50IHN0YXRpYyBjb2RlIGNoZWNrCgojIyBPbiBDaGVja3MKClRoaXMg\ncmVwbyBjb250YWlzIGEgc2V0IG9mIHNjcmlwdHMgZm9yIHZlcmlmaWNhdGlv\nbiBvZiBhbGwgdGhlIGluZm9ybWF0aW9uLiAgSW1wbGVtZW50ZWQgYXMgVHlw\nZXNjcmlwdCBzY3JpcHRzLCBhdmFpbGFibGUgdGhyb3VnaCBgbnBtIHJ1biBj\naGVja2AsIGFuZCBleGVjdXRlZCBpbiBDSSBidWlsZDsgY2hlY2tzIHRoZSB3\naG9sZSByZXBvLgpUaGVyZSBhcmUgc2ltaWxhciBjaGVjayBsb2dpYyBpbXBs\nZW1ldGVkOgotIGluIGFzc2V0cy1tYW5hZ2VtZW50IGFwcDsgZm9yIGNoZWNr\naW5nIGNoYW5nZWQgdG9rZW4gZmlsZXMgaW4gUFJzLCBvciB3aGVuIGNyZWF0\naW5nIGEgUFIuICBJbXBsZW1lbnRlZCBhcyBhIFR5cGVzY3JpcHQgbGlicmFy\neSwgY2hlY2tzIGRpZmZzLCBjYW4gYmUgcnVuIGZyb20gYnJvd3NlciBlbnZp\ncm9ubWVudC4KLSBpbiBtZXJnZS1mZWUtYm90LCB3aGljaCBydW5zIGFzIGEg\nR2l0SHViIGFwcCBzaG93cyByZXN1bHQgaW4gUFIgY29tbWVudC4gIEFsc28g\ndXNlcyBsaWJyYXJ5LCBidXQgZXhlY3V0ZXMgaW4gYSBub24tYnJvd3NlciBl\nbnZpcm9ubWVudC4KCiMjIFRyYWRpbmcgcGFpciBtYWludGVuYW5jZQoKSW5m\nbyBvbiBzdXBwb3J0ZWQgdHJhZGluZyBwYWlycyBhcmUgc3RvcmVkIGluIGB0\nb2tlbmxpc3QuanNvbmAgZmlsZXMuClRyYWRpbmcgcGFpcnMgY2FuIGJlIHVw\nZGF0ZWQgLS0KZnJvbSBVbmlzd2FwL0V0aGVyZXVtIGFuZCBQYW5ja2Fzd2Fw\nL1NtYXJ0Y2hhaW4gLS0gdXNpbmcgdXBkYXRlIHNjcmlwdCAoYW5kIGNoZWNr\naW5nIGluIGNoYW5nZXMpLgpNaW5pbWFsIGxpbWl0IHZhbHVlcyBmb3IgdHJh\nZGluZyBwYWlyIGluY2x1c2lvbiBhcmUgc2V0IGluIHRoZSBgY29uZmlnLnRz\nYCBmaWxlLgpUaGVyZSBhcmUgYWxzbyBvcHRpb25zIGZvciBmb3JjZS1pbmNs\ndWRlIGFuZCBmb3JjZS1leGNsdWRlIGluIHRoZSBjb25maWcuCgojIyBEaXNj\nbGFpbWVyClRydXN0IFdhbGxldCB0ZWFtIGFsbG93cyBhbnlvbmUgdG8gc3Vi\nbWl0IG5ldyBhc3NldHMgdG8gdGhpcyByZXBvc2l0b3J5LiBIb3dldmVyLCB0\naGlzIGRvZXMgbm90IG1lYW4gdGhhdCB3ZSBhcmUgaW4gZGlyZWN0IHBhcnRu\nZXJzaGlwIHdpdGggYWxsIG9mIHRoZSBwcm9qZWN0cy4KClRydXN0IFdhbGxl\ndCB0ZWFtIHdpbGwgcmVqZWN0IHByb2plY3RzIHRoYXQgYXJlIGRlZW1lZCBh\ncyBzY2FtIG9yIGZyYXVkdWxlbnQgYWZ0ZXIgY2FyZWZ1bCByZXZpZXcuClRy\ndXN0IFdhbGxldCB0ZWFtIHJlc2VydmVzIHRoZSByaWdodCB0byBjaGFuZ2Ug\ndGhlIHRlcm1zIG9mIGFzc2V0IHN1Ym1pc3Npb25zIGF0IGFueSB0aW1lIGR1\nZSB0byBjaGFuZ2luZyBtYXJrZXQgY29uZGl0aW9ucywgcmlzayBvZiBmcmF1\nZCwgb3IgYW55IG90aGVyIGZhY3RvcnMgd2UgZGVlbSByZWxldmFudC4K\n

**Comment by thisIsTheFoxe** [comment]
The problem seems to be that you have newlines in there, which for some reason [aren't ignored](https://github.com/SwifterSwift/SwifterSwift/blob/ff8bfc636b01083cc85dc56d88e40a0068714383/Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift#L36).


[Try it online!](https://tio.run/##jVlZc@JI1n2e@hWMv5iIquiaaklAj6mI/iYsbC0YVA2UtYVftGAJSAkVEouYmN/ec26mxFLVPTF@sY2UmXc599xzk/KwfKt6v/@@zIrNtupom10eB9Vyk797V@xCtow6i2O1yEt80plX22WedP71roOfn3/@uTOnxYst//W5fRwvok28iDtv203WCYNy8Uuv83751gmKAtsFIVt8@NTu0P7@y1/u5rpdhvp9YiuDOtSn6d0nsfax2e7XzpeC7ArY@ztjwdim42y2LP7r3YebzfbBtnOzsLXrn43d9MMWVWe7yIJlHi@22DmC11Xnb53eu/MrtE8RxDF59Gvn7u78AJ5clv5/R7raln4ua8Sx77eLYoGA5snnzt2vdx/FWZ87vc7fL/t8OG/x74sFyS7YxtxUJCTAho/49V749pQ3vpUL9tb5qT31440pP/5seATLz51PyyTfbBcv@TrfHPJhGmyDCIksP3QWrFx0/gXTqt027@RLdm1S82njGZn1mRv3sbMgg7iTn3bV271w6N/vsPbdO3KhpCCatfoS5fYpHqqu5xxL350mU9c6@e7sZD6xnZ/dPw@XWjhVUuYpVfysp1JsqKcvy/v9a@4rTAoMeznOrH04H0h8JyNOQ/3I4uEgjboWi43JPgaAAsUvw258GkvWxnes7Ws@Vkapr8dsnFuKX69xzmRlPg0U3x0pgWN3h2xWx64lmVq7oyqFSsXCpVrjbFfdRzg/7I76ps5Opv6UeMqgiowRC3R7h2eKPz8ksftQxfp95eua5M/VVagcS6x2LClwBjtTH2RYDT8BcUdrPtOWYdeWTAPWZ3btOdhFT/ewJQ2z2ek1N4dJ@jxX9/5SXUU5O2B/vDHY@k7/NE42z478neWatAmMmRQZk1/gd/19pPqwSipMw0bcJ81OvSTUB3nYnSR@PkJ0VSmAlzjbsGDJaEW@IWP7MItPgTNj5H@Y25UHi4VXA6zA34Zah0rBvC5ZTtbZespMRCnSB6fAne2jfE2R28W6VoT55fzA6WdhrWZRNqgoFq95Gw0vO@6BhlUgVpQigvdJqPQS/0k7wM8SKyTPqYowi5I40xBzWJli7zqqDwnwtRonhR52TfztM7KhPdebq2WoxHvkYecPkWVjVrzmodJPw6EKxMyKWGfwWyt/zBzhQFM8h5WeMyr9@cMm6tornD1U1547S8Ub/T2wlMKqIqRc6y9keeUpaRo4vYJi9IJVWIP3j@lrHmUx4guMI1uIY0F@eoqG80b4XMaqPnyFLc4UO/XLBWXLGO1jJ94gYw0yQ9feId5Aq52R1fHwkETKfeIqPvMRVeSZAaESYg4vp8nCGcg4e9mgnt3vhsnm3lNsZMquf1sdi9CJkqg7Wv02jzexMTtEp81@3BXYixWKeajbUlOd52oMHDn1Ffs0VmTm6ywdK9opUmwpqgcbVFOxyDgWsNpVRmXsvOwivZ@PahV1y/LAmA7MlXmYDM2ffhsOVsC85LvmT7BtBTYxwy7yjXp4zT1ntjaN2T6AxcOkmMKWNFIQ62xAlQh0aqiQwZuXj1BXiFxmd9v34TeiEGXibeR0Bb9RZ/bale/LYT7bYIcDkPmNKhnvbjygiFZTTpoqcfrr8VDtIuabP6jxK5RQJfXXZAtOw9ljRwZuWcWxrrDa69ol0IO899/cw2ZDOwEZiD@DbTPGK8eYIJs2nX3Fkdd5H@eXzFzlRRor4JZaRt5lVGjsjKrAnVbeXG7YTubVMD5NetZqwtFp1sSUbdZUNTIensGWwBqiEp7524iZt0QUDfWGt73m@ff2wG9u0fqCbWIkYFr4K@@j7m2WEMU1EMQjShl72MyajiAyNpDDfJoE4DSsAtbs9fO8J3i@Vmexw1ZBrZ4QPfA5YRooeYJlqKfjiXOYwfNc33A9eAXsuYoNu8YzjhxgjfjLGBVebjf5jWVixZDyjvM9lyr1WETdGSNOQQ8B/l6eHWkmeA29SQULUQ6Z5NsXvgZbr4mhwMYH4JxOkbFLt@mWO352hRpa@9oAZ8VvIr5TZKowfX6u6E6RaxeeUqJiZ2mUzxgqm@dbrmAdWMHfR8KqJHQG1JHRFeSKuAZZIv6h6iEO@Pa85nHH2T6qBL5oL@tJPbn0RzAz@Eshf6ffnleb5zFwYWpS8tXRtojaCR2EVwlDLzHhs0wW4by@FGXaCmejniZkR91U6s58NEvr68OB59yg1RF6U6APSuSVc3rYRbbcEeoN1tLOc9QeoiSQhK6cIWvAwHApIWNOrcbmE3zOSuquzHyKweupDMTe5JveFu9ate/wHp5RNzgiK2YSE96G6s5zZNYgRiDTsCiqUtPXyCPqHNjZoh6K2Jla9eYJVXOKHSlp2cGV/3vuye9L9v8k96vLzvJbuzMUAyH1tnfugXeKGoMNl8o8HRvOH5ywso6p96BaiVMtyVVEBhD/n8bKw@4cIY3wfuB9A0iC5VbhK30mUKVJlO@2bonbqKfJMtW0B55F50tenvoGx2Emp9SdwKnoFtMEfqMLhrl1oDqimvaAkkCJa@gk9Gj0MeSW0IpusCbGQPZ@Qfetra9@b7J6URA1IympVy6GvcT6@lQvHl@Ok1ztXRianqkZEAO0WOhC1JW9ZALMoX9LZtlUSAbsCmVzzbyZnaKuQ9HbXhIwBPJjcd5DjTXMB6QqPjRThNV/wsaEkjfiOLfpioiaIqI1hu9UwziL/ATzrq9ibx@AErKhj5hQd9j7CnXBBqHCLx0axrHXpi4UzjhXd77ywPsl6dY4o3q0SD@syCPOimvyO9Q5X4hIXWMbmfEog@i1WHGiOuS9TGdZU99zdY26xtnwkzilO6qpZ4bGukUKssp3RfdH1IZk22BLVXIsAsQSVVlENRSPPsITayt0EpQuokN58F27umiI@8Pi8QlInZymsrWKJGulrSeK15vpZtd6XCvW1@RonSJpmk3Rz9jjl0fryfqqrb58ney54q37yDdUbfIHld9o0v63CL57Z7QQcyStXk2pxgYyTQvEpY2qhIoc7TkDPWwqUysTd64@UoxjvAPFeYiJqQSvuTajqhCqPm0UXo8wdggP59VTz12L51xhW1hjkU6F3vXR7Ro99IQnMnJOLMQ707BVvcAcKRDKGOkG6nWif8@uUIruThqdufP0ovCUGTt3rGX/PEuQ2jtPE3tChIu8x3Kj/IbrX2ATrK8eBc@zZewKLet3bVgOi0rEkEXy/979Wv7D6h8Y8LYjj52bjlw0tsyJ6xHz8yTX1rR1o1n@W@W2uuXH2jW7N1NOdYl5M21q1orUPSY4Y8IVlOjXGnW9E59LaMowgGPxDjEiqZMULM6oLrk@r0j7c6sxHyFDz4RcT@8fMLXVMU00ohsk5lCqzCe7h/qTCXekPLRSzEVsf@7b3ck/qFppNqDOj4os6BllDfmRUaUnk3d/sAOsF7gaUzx1FVpdIvYDx4s5e8ynViYtnIdkPJeSF8wHAeqfa2TZywkZYpJtziatgElSxcw3knFuFripsFwD3jLqDtS/PddGj5LJ8hUiUSx0mxSniKCB/o1qoCh9Hws/Yz1k7E@sop6OiW1J2ft@ZezyGQ4VOuVnNyu5rxriOahIo3u1Kkc6RZSi5KMy0dvdFDuPdqTnCWtgvQz1yudQZAazPu9ZmQ01dsTUceybw9QAaszYMROvuSt4nm4qYsWrGBv2gd8rONe2yCnmcJpVf7CDbi0ultzYIRT2ZSUpvYv/WEMZ84YPFbIzp2hEilUHrirBBkwXxFbEAlfZo/kknzWZI92CXE5oUuWTuYgUMEU3BwIpDWP9hvceWyxQTZB@pyoB@9UChcC7ULRUY1x1XSqEe2JQ5TCws8WRzc8mjKWkTwSn3s5j4@VDMndk9FDRWykfpEBtgx0oas3@Q/XkYUKNDGik7yZ47EpqhCb9a/TS7M@18EPZ3CcwIHUF5mvr6nE@V5eYRUr/sWwr9dRMHl1aDYXbzCBQ9C@8483FbArWqogNorZ6at7XKbJF6Kr8nklm1MO/8OpkhNSmT0L1O32aw7m/@PwQ4XyBg/aGDNnK6T@8mVNE2hsS1FBJUw3XbNqIYrHn6kDndc@7Zbv6CW@YO3OojsgisgeoIN9TmrChGfvg1CaqmO50tgSjoH8vaCpuo6HPCj/z6ZyVR3yWvTQcI3CNCX4fo8fABuzuF4SWwY53vWGPEElxroB79Dc5852XCh1a4soP7IGMob77dHPDUfWa0xQ5F1PkIULOkYMurCX1LoewUvhtilsVcUqCeZgzJljRpZpSwaujmiYrnINON73UehM5dP0dv/e5sp5Url9cWy/6xKxGP@V3WRF4/sL5Niq5v/Knm@c51AdW13y2xHylHtDPOI5Jo9G0hlntgFV1e7OBPgouJX1HuFAlmmqg@TM@te2CHD0te2hzvaPb0BsbMKtezelUJZyJpsREz82doQ2OPaFPHsbSRas1dTAlywN0SnoORpZbVclvwTifIZLi/q5h3nOdDx82QmXeIpXtzmh16aaisPB5gRovz7clhp@Ghk35yUgFicniOjq0i6ccwYC8IzZ1RjyD3UVV8ttKxCWHEjgRKwod@H11QqOcKB90fwjWOrXzA/KyAg7hmVXS/E0MyCPSPgFDWKX4/Hwm8R5OiXatrsOUuyLFBQZy7PqP7qpRhRVX3QK94Ha6tXwRah89Dqv5/RE0GiFC3M61qrMQeL/MweMl3a3F/EYaiKb65vcKs73P71folkxmVJ1YjelN7bZxoGwiwlz1ozPTpE83B@4IdcUOrXr2@KR@vnO5ulvrPX/vHaLW@ofVxOnA8bdm//NtM@3kudPm7gWcA@4h3uF3eydgF9EhtvNRpfYanVdMlo7PVQCew2JfRjdEHPzCdyNeA7y@f4wzzcOKXSM6LXdDT8Qb/p1BTeyMDCtccXHFjmkqk8UdU8PIXA1lckG6RaBFI1be8btcfrswk7k@v9qPo5aqZkvfm3BUNrdhXNWj9tARqO9l4FRaPaRbElIU/f75fl73McGRPkXuYSE0KiPFA7WLXGucg17zO/GdzTazxp1fO@Wn7aJgQbTMky9RtNtuF3m0KN9v3j537l5fy7uPncOySvEP/rp8wbRdJDsWbJ@OxXZR0reHHzvbIE8Wn@k7pQ/v3hXbZV69vyvpK7Hy9qu@j9g3f83/7/IDky5LyCxaRb9vF374/ff/AA "Swift – Try It Online")

**Comment by thisIsTheFoxe** [comment]
The problem is that the padding from #801 doesn't ignore non-base64 characters (like newlines aka `\n`) adding a wrong padding. 
[Try it online!](https://tio.run/##rZJfa9swFMWfo09xp1GwWeqUEUpmSEtptuytjKzpS1/k6NoVVSQjyctGyGfPJP@Jm2Z7Kb0vwpLu0e/cY7sRuRvv92JdauPgm64UZ05oRUhZZVKsAH87VNbvwMIZoQrYEvA1Go1gEZrR1EvaHXNcaY4ccqPXkDGLl2OIRA6sLL0cyyTGSafQrYMBXcyXNptPiuXnL3@y@Y8nmjS9s1ZuCndl4GIyot9RSg0P2kj@gcZHYr@YgaPGjuu65Q4l0YHBNROKo/HKK@/awRmMyeFK0CkZ58HRFCg9HHgnfesVXLyQDdX3NM9GBkv0A1VFCnRKh81bKYzhvNeJDxK7nqComOE1qg@EecGZX6LG21fVerMoc/jUvTo8QjktXU/QppCIQmmD9@pZ6Y26fWKGrXyQNgaUFmHr0VxlFCghXyK1u62zgJXWcEPAAFSbTCqXTxpDO@J7CQkWbBjiScSenF4/KkpeB2KTPpKTJP6RwOCNY9@R0t92ke1nGHdbDUL3ST825X@3mpb/L5D3TKN7e3bz8yZ9jHhM4/3@Lw "Swift – Try It Online")

**Comment by Jayxiang** [comment]
You can ignore non-base64 characters (like newlines aka \n) first.
```
str.withoutSpacesAndNewLines.base64Decoded
```
