### ISSUE TITLE
func init(randomOfLength length: Int) bug

### ISSUE THREAD

**Issue by fanglinwei** [SwifterSwift/SwifterSwift#994]
When I call `map(string.init)`, it will call `init(randomOfLength length: Int)`, which is not what I want

![image](https://user-images.githubusercontent.com/16839723/138276401-fbe7badf-54d3-4a38-97f0-5f74d60d1ae5.png)

![image](https://user-images.githubusercontent.com/16839723/138276436-ba392b34-de5a-4ad9-863b-d1a3f2bd5c39.png)

**Comment by LucianoPAlmeida** [comment]
Hi @fanglinwei,
Sorry for missing out on this, are you still having this issue?
If yes what overload of string init would you expect to be picked? Because as far as I know there is no overload in the stdlib at least that takes an integer. So maybe it is calling this overload because it is the only one that matches in context :)
